//
//  MKPuzzle.h
//  Dream Puzzle
//
//  Created by iMacPro05 on 26/8/13.
//  Copyright (c) 2013 iMacPro05. All rights reserved.
//

#ifndef Dream_Puzzle_MKPuzzle_h
#define Dream_Puzzle_MKPuzzle_h

#define MKMathDegreesToRadians(degrees) (degrees * (M_PI / 180))

enum
{
    PIECE_SHAPE_PPPP,
    PIECE_SHAPE_PPPM,
    PIECE_SHAPE_PPMP,
    PIECE_SHAPE_PMPP,
    PIECE_SHAPE_MPPP,
    PIECE_SHAPE_PPMM,
    PIECE_SHAPE_PMPM,
    PIECE_SHAPE_MPPM,
    PIECE_SHAPE_PMMP,
    PIECE_SHAPE_MPMP,
    PIECE_SHAPE_MMPP,
    PIECE_SHAPE_PMMM,
    PIECE_SHAPE_MPMM,
    PIECE_SHAPE_MMPM,
    PIECE_SHAPE_MMMP,
    PIECE_SHAPE_MMMM,
    PIECE_SHAPE_SPPP,
    PIECE_SHAPE_SPPM,
    PIECE_SHAPE_SPMP,
    PIECE_SHAPE_SMPP,
    PIECE_SHAPE_SPMM,
    PIECE_SHAPE_SMPM,
    PIECE_SHAPE_SMMP,
    PIECE_SHAPE_SMMM,
    PIECE_SHAPE_PSPP,
    PIECE_SHAPE_PSPM,
    PIECE_SHAPE_PSMP,
    PIECE_SHAPE_MSPP,
    PIECE_SHAPE_PSMM,
    PIECE_SHAPE_MSPM,
    PIECE_SHAPE_MSMP,
    PIECE_SHAPE_MSMM,
    PIECE_SHAPE_PPSP,
    PIECE_SHAPE_PPSM,
    PIECE_SHAPE_PMSP,
    PIECE_SHAPE_MPSP,
    PIECE_SHAPE_PMSM,
    PIECE_SHAPE_MPSM,
    PIECE_SHAPE_MMSP,
    PIECE_SHAPE_MMSM,
    PIECE_SHAPE_PPPS,
    PIECE_SHAPE_PPMS,
    PIECE_SHAPE_PMPS,
    PIECE_SHAPE_MPPS,
    PIECE_SHAPE_PMMS,
    PIECE_SHAPE_MPMS,
    PIECE_SHAPE_MMPS,
    PIECE_SHAPE_MMMS,
    PIECE_SHAPE_SSPP,
    PIECE_SHAPE_SSPM,
    PIECE_SHAPE_SSMP,
    PIECE_SHAPE_SSMM,
    PIECE_SHAPE_PSSP,
    PIECE_SHAPE_PSSM,
    PIECE_SHAPE_MSSP,
    PIECE_SHAPE_MSSM,
    PIECE_SHAPE_PPSS,
    PIECE_SHAPE_PMSS,
    PIECE_SHAPE_MPSS,
    PIECE_SHAPE_MMSS,
    PIECE_SHAPE_SPPS,
    PIECE_SHAPE_SPMS,
    PIECE_SHAPE_SMPS,
    PIECE_SHAPE_SMMS
};

#endif
